spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 4000MB
      max-request-size: 4000MB
  datasource:
    #驱动类
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #url
    # url: jdbc:mysql://127.0.0.1:3306/testdb
    url: jdbc:oracle:thin:@localhost:1521:orcl
    #用户名
    username: C##ZHOU
    #密码
    password: C##ZHOU


#mybatis配置 在控制台打印日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zhouzz.pojo
  mapper-locations: classpath:mapper/**/*.xml


#开启打印sql 语句 日志 级别为DEBUG
logging:
  level:
    org:
      apache:
        ibatis: DEBUG
      mybatis:
        spring: DEBUG

#配置redis
redis:
  host: 127.0.0.1 #redis地址
  port: 6379 #redis端口
